### ISSUE TITLE
[Feat] - Emoji fit in two array emojiUrls

### ISSUE THREAD

**Issue by dandamdandam** [keepgoingLikelion/emotionDiary_backend#12]
## 필요한 기능
- [x] emojiType(String[]), emojiUrls(String[][]) 더미데이터를 EmojiService에 추가
- [x] emojiEntity 수정
- [x] getEmojis 수정

# 추가 컨텍스트
현재 이모지 컨트롤러와 내가 바꾸고 싶은 방향의 구체적인 예상 api 호출 횟수, 메소드를 작성해야 하는 법칙을 곁들여 설명.

### DTO
- emojiUrlResponse
	- emojiUrls: `String[][]`
- EmojiInfoResponseDto
	- id: Long
	- x: double
	- y: double
	- emojiIndex: Long
### api 목록
- 전체 이모지 리스트 - get `/api/emoji`
```JSON
res{ EmojiUrlResponse }
```
- 이모지 달기 - post `/api/saveEmoji`
```JSON
req{
	x: double,
	y: double,
	emojiIndex: Long,
	Long: postId
}
```
- post getById - get `/api/{postId}`
```JSON
req{
	post요소들...,
	comments: emojiInfoResponseDto[]
}
```

### emoji type의 이미지를 불러올 수 없음
전체 이모지 리스트의 리턴을 이차원배열로 한다고 해도, 아래 파란색 동그라미의 이미지를 불러오기엔 힘듬
![[KakaoTalk_20240207_182637568.jpg]]
ex) `[[type1에 대한 이모지들][type2에 대한 이모지들]....]`
	- 파란색 동그라미 쪽에 넣을 이미지가 없다...
- 제안1
	- 전에 적은 것처럼 type의 이미지만 불러오는 get과 type에 대한 이모지를 돌려주는 get을 분리
- 제안2
	- emojiUrlResponse에 emojiType을 추가
		- emojiTypes: `String[]`
		- emojiUrls: `String[][]`
		- ex) emojiTypes: `[type1의 이미지, type2의 이미지...]`
		    emojiUrls: `[[type1에 대한 이모지들][type2에 대한 이모지들]....]`

### emojiUrl이 이차원 배열일 경우, emojiIndex는 두개가 필요하다
- 말 그대로 입니다. `[emojiIndex1][emojiIndex2]`이렇게 2개를 저장해야 합니다.
- 이왕 늘리는 김에 emojiIndex1, emojiIndex2보다는 emojiTypeIndex, emojiIndex이름으로 하는게 가독성에 좋을 듯합니다.

### 클라이언트의 보이지 않는 의존성
- 현재 서버에서 제공하는 post getById를 통해 얻은 데이터로 이모티콘 이미지를 불러오려면 클라이언트에서는 다음과 같은 작업을 해야합니다.
```js
const Page = () => {
	let emojiUrls = [
	            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type.png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(1).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(2).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(3).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(4).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(5).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(6).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(7).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(8).png",
            "https://emotiondiary-bucket.s3.ap-northeast-2.amazonaws.com/%ED%91%9C%EC%A4%80type+(9).png"
	]
	// api를 가져오는 작업
	// emoji의 경우 위치에 따라 css를 조정하고 emojiUrls[emojiIndex]로 이미지 할당
}
```
- 지금 위에건 일차원 배열인데 만약 이차원배열에 이모티콘 타입이 추가되면 더 길어집니다.
- 또한 이모티콘을 추가하거나 삭제한다고 치면 서버의 EmojiService 배열과 클라이언트 이모지 배열을 둘다 고치고 다시 배포해야 합니다. -> 의존성 관리 상 별로 좋지 않은 코드가 될 것 같습니다...
- 제안
	- EmojiService에 다음과 같은 get 함수를 추가하면 emojiIndex 대신에 emojiUrl을 직접 줄 수 있습니다.
```java
String[][] emojiUrls = {초기화....}

public String getEmojiUrlByIndex(int emojiTypeIndex, int emojiIndex){
	return emojiUrl[emojiTypeIndex][emojiIndex];
}
```

**Comment by GamJaDo** [comment]
일단 구현해보고 스크럼 회의때 설명하겠습니다
