### ISSUE TITLE
[Feat] post implement 2 (connect with user and emoji)

### ISSUE THREAD

**Issue by dandamdandam** [keepgoingLikelion/emotionDiary_backend#8]
## 필요한 기능

- [x] post TODO들 - user 정보 가져오기
- [x] createdPost - 유저의 이전 글이 있는지 확인 후 post하는 절차 추가
- [x] 로그인된 유저의 오늘 글 get
- [x] 마이페이지 그땐 머랭 용 get

### 서버 내 userEntity get에 대해
- [createdPost](https://github.com/keepgoingLikelion/emotionDiary_backend/blob/main/src/main/java/com/keepgoingLikeline/emotionDiary_backend/service/PostService.java#L40) 함수에서 userEntity를 가져와 저장을 합니다. [userController 내의 get 함수](https://github.com/keepgoingLikelion/emotionDiary_backend/blob/main/src/main/java/com/keepgoingLikeline/emotionDiary_backend/controller/UserInfoController.java)를 쓰라고 하신 것은데, service 파일에서 controller의 함수를 가져다 쓰는게 이상해보이지 않나요?

**Comment by GamJaDo** [comment]
컨트롤러랑 서비스를 분리해서 사용해야하는데 jwt토큰이 제대로 사용되는지 테스트를 하려고 그냥 컨트롤러에다가 다써버렸네요
저거는 그냥 분리를 하면 될것 같습니다.
이번에 emoji추가할때 어떤 사용자가 emoji를 추가했는지에 대한 작업을 할때 저부분은 컨트롤로와 서비스를 구분해 놓겠습니다

**Comment by GamJaDo** [comment]
그리고 현재 getCurrentUser메소드는 현재 로그인되어있는 사용자의 email정보를 가져오는 메소드인데 
자신이 오늘 작성한 글을 불러올때는 현재 로그인되어있는 사용자의 오늘 작성글을 불러오는 메소드를 getCurrentUser메소드의 형식을 따라 작성하시면 될것 같습니다
